# Generated by Django 2.1.5 on 2019-02-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_scoree',
            field=models.CharField(choices=[('AMK', 'Annaleise'), ('TDS', 'Tobin'), ('BTH', 'We both')], default='BTH', max_length=3),
        ),
        migrations.AlterField(
            model_name='point',
            name='point_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='point_value',
            field=models.SmallIntegerField(default=1),
        ),
    ]
